### PR TITLE
added my name

### PR DESCRIPTION
**Pull request by Pdahiya5033**

### CODE REVIEW

**Comment by Pdahiya5033** [comment]
done

**Comment by Pdahiya5033** [comment]
edited contributor.md

**Comment by Pdahiya5033** [comment]
accepted

**Comment by Pdahiya5033** [comment]
[README.md](https://github.com/anubhab1710/Beginner-Repo/files/7963539/README.md)

**Comment by anubhab1710** [comment]
Good work!

**Pull request merged**
